### PR TITLE
[ci skip] Pin toolchain

### PR DESCRIPTION
**Pull request by isuruf**
Please ping conda-forge/toolchain team (with @ notation) for any clarifications

### CODE REVIEW

**Comment by isuruf** [comment]
@183amir @conda-forge/toolchain how about automated PRs like this? I'm using the following script.
```
hub fork
git checkout -b toolchain
sed -i -- 's|- toolchain 2.0.0|- toolchain|g' recipe/meta.yaml
sed -i -- 's|- toolchain|- toolchain 2.0.0|g' recipe/meta.yaml
git add recipe/meta.yaml
git commit -m "[ci skip] Pin toolchain"
git push isuruf toolchain
echo -e "[ci skip] Pin toolchain\n\nPlease ping conda-forge/toolchain team (with @ notation) for any clarifications" | hub pull-request -F -
```

**Comment by 183amir** [comment]
Why is circle ci still running? Maybe you have to put `[skip ci]` instead.

**Comment by 183amir** [comment]
Sorry it looks fine

**Comment by 183amir** [comment]
I think this scheme is ok.

**Comment by isuruf** [comment]
Thanks @183amir. @jakirkham, @ocefpaf, can you have a look as well, before I create 407 PRs?

Ref: https://github.com/conda-forge/toolchain-feedstock/pull/11

**Comment by isuruf** [comment]
Ping

**Pull request closed without merging**
